quarkus:
  log:
    level: WARNING

storm:
  urls:
    - www.google.com
#  order: random # or sequential or roundrobin
#  order: sequential
#  order: roundrobin
#  threads: 10
  repeat: 1
  categorizers:
#    - httpcode
#    - regexpmatch(.*( (a|the) ).*)
#    - body
#    - header(server)
    - URL
#    - durationhistogram(10)
  stats:
    - count
#    - time
#    - durationsum
#    - headers
#    - durationstats

