quarkus:
  log:
    level: WARNING

storm:
  urls:
    - http://metaphorpsum.com/paragraphs/1/1
    - http://httpbin.org/status/400
#  order: random # or sequential or roundrobin
#  order: sequential
#  order: roundrobin
#  threads: 10
  repeat: 100
  categorizers:
#    - httpcode
#    - regexpmatch(.*( (a|the) ).*)
#    - body
#    - header(server)
#    - URL
    - durationhistogram(5)
  stats:
    - url
    - count
#    - relativecount
#    - time
#    - durationsum
#    - headers
#    - durationstats

