quarkus:
  banner:
    enabled: false
  log:
    level: "OFF"
    console:
      format: "%d{HH:mm:ss:SSS} %m%n"
      #format: "[%p:%t{id}] %d{HH:mm:ss:SSS} %m%n"
    category:
      "org.someth2say.storm":
        level: INFO
      "org.someth2say.storm.stat":
        level: WARNING
      "org.someth2say.storm.category":
        level: WARNING
      "org.someth2say.storm.configuration":
        level: WARNING

## Those can be used to set default values
# config-file: /Users/jordisola/Downloads/flare/storm.yaml
# dump-config: 
# urls: 
    # - http://www.thisurldoesnotexits.com
    # - http://metaphorpsum.com/paragraphs/1/1
    # - http://httpbin.org/status/400
# proxy: "proxy.example.com:80"
# connect-timeout: 100
# request-timeout: 100
# redirect: NORMAL or ALWAYS or NEVER
# order: RANDOM or SEQUENTIAL or ROUNDROBIN
# threads: 10
# repeat: 10
# delay: 100
# categorizers:
# - httpcode
# - regexpmatch(.*( (a|the) ).*)
# - body
# - header(server)
# - URL
# - durationhistogram(5)
# - timehistogram(200)
# stats:
#  - urls
#  - count
#  - errors
#  - relativecount
#  - relativeduration
#  - time
#  - durationsum
#  - headers
#  - durationstats
