quarkus:
  banner:
    enabled: false
  log:
    level: "OFF"
    console:
      format: "%d{HH:mm:ss:SSS} %m%n"
      #format: "[%p:%t{id}] %d{HH:mm:ss:SSS} %m%n"
    category:
      "org.someth2say.storm":
        level: WARNING
#      "org.someth2say.storm.stat":
#        level: DEBUG
#      "org.someth2say.storm.category":
#        level: DEBUG
#      "org.someth2say.storm.configuration":
#        level: DEBUG


## This config sets sane defaults for configuration entries.
storm:
  ## Those can be used to set default values
  # config-file: /Users/jordisola/Downloads/flare/storm.yaml
  dump-config: false
  urls:
#  - http://www.thisurldoesnotexits.com
#  - http://metaphorpsum.com/paragraphs/1/1
#  - http://httpbin.org/status/400
  - http://localhost:8080/status
  # proxy: "proxy.example.com:80"
  # connect-timeout: 100
  # request-timeout: 100
  # redirect: NORMAL or ALWAYS or NEVER
  # order: SEQUENTIAL #RANDOM or SEQUENTIAL or ROUNDROBIN
  # threads: 10
  # count: 100
  # duration: 1000
  # delay: 100
  categorizers:
    - httpcode
  #  - regexpmatch(.*( (a|the) ).*)
  # - body
  #  - header(server)
#    - URL
#    - durationhistogram(5)
  #  - timehistogram(200)
#  stats:
#    - count
  #  - duration
  #  - durationsum
  #  - errors
  #  - headers
  #  - id
  #  - relativecount
  #  - relativeduration
  #  - time
  #  - urls



